/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keg_checkjni_JniManager */

#ifndef _Included_com_keg_checkjni_JniManager
#define _Included_com_keg_checkjni_JniManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keg_checkjni_JniManager
 * Method:    checkFactorialFunctionTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_keg_checkjni_JniManager_checkFactorialFunctionTime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
